//! CKBoost shared types
//!
//! This module provides a clean interface to the generated Molecule types
//! for CKBoost campaigns, quests, and protocol data.

// Re-export all generated types from the generated module
pub use crate::generated::*;

// Organize exports by functional area for better discoverability

/// Basic blockchain types (CKB primitives)
pub mod blockchain {
    pub use crate::generated::{
        Block,
        BlockV1,
        Byte32,
        Byte32Opt,

        Byte32Vec,
        Bytes,
        BytesOpt,
        BytesVec,
        CellDep,
        CellDepVec,
        CellInput,
        CellInputVec,
        CellOutput,
        CellOutputBuilder,
        // Add other readers/builders as needed
        CellOutputReader,
        CellOutputVec,

        CellbaseWitness,
        Header,
        OutPoint,
        ProposalShortIdVec,
        RawHeader,
        RawTransaction,
        // CKB core types
        Script,
        ScriptBuilder,
        ScriptOpt,
        // Readers and Builders
        ScriptReader,
        ScriptVec,
        Transaction,
        TransactionVec,
        Uint128,
        Uint256,
        Uint32,
        Uint64,
        // Basic types
        Uint8,
        // Vectors
        UncleBlockVec,
        WitnessArgs,
    };
}

/// Campaign and quest related types
pub mod campaign {
    pub use crate::generated::{
        AssetList,
        AssetListBuilder,
        // Readers and Builders
        AssetListReader,
        AssetListVec,
        CampaignData,
        CampaignDataBuilder,
        // Add other readers/builders as needed
        CampaignDataReader,
        CampaignDataVec,

        CampaignMetadata,
        QuestData,
        QuestDataBuilder,
        QuestDataReader,
        QuestDataVec,
        QuestSubTaskData,
        QuestSubTaskDataVec,
        UDTAsset,
        UDTAssetBuilder,
        UDTAssetReader,
        UDTAssetVec,
        UserSubmissionRecord,
        UserSubmissionRecordVec,
    };
}

/// Protocol governance and administration types
pub mod protocol {
    pub use crate::generated::{
        ProtocolData,

        ProtocolDataBuilder,
        // Add other readers/builders as needed
        ProtocolDataReader,
        TippingProposalData,
        TippingProposalDataBuilder,
        TippingProposalDataReader,
        TippingProposalDataVec,
        TippingProposalMetadata,
        UserVerificationData,
        UserVerificationDataBuilder,
        // Readers and Builders
        UserVerificationDataReader,
    };
}

/// SSRI transaction recipe types
pub mod ssri {
    // TransactionRecipe is now provided by ckb_deterministic
    pub use ckb_deterministic::generated::TransactionRecipe;
    // Note: TransactionRecipeReader and TransactionRecipeBuilder are auto-generated by molecule
    // and available through the TransactionRecipe type's associated methods
}
